
import "@/styles/globals.css";
import "@/styles/index.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body  className="max-h-screen">{children}</body>
    </html>
  );
}
